### ISSUE TITLE
想请教一些ego-planner代码上的问题，能留个联系方式吗

### ISSUE THREAD

**Issue by pzx-Id** [DoubleMuch/mjd_ego_planner#1]

**Comment by DoubleMuch** [comment]
我的微信Double-Much，我也在学习阶段，可以一起讨论下








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DoubleMuch/mjd_ego_planner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月20日(星期天) 晚上8:39
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [DoubleMuch/mjd_ego_planner] 想请教一些ego-planner代码上的问题，能留个联系方式吗 (#1)





 
Closed #1.
